import { Item } from "./item";
import {
    InstrumentoEnum, DificultadEnum, TipoEnum,
    HambreEnum, PreparacionEnum, SaborEnum
} from "./categorias";

export const ITEMS: Item[] = [
    {
        id: 1,
        nombre: "Omelette",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Jamón", "Queso", "Champiñones", "Espinaca"],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 3,
        imagen: [],
        ingredientes: ["Huevo"],
        link: [],
        tipo: [TipoEnum.desayuno],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 2,
        nombre: "Chuleta de Cerdo",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["BBQ", "Salsa de Limón, Mantequilla y Jalapeño"],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 3,
        imagen: [],
        ingredientes: ["Chuleta de cerdo"],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 3,
        nombre: "Cereal",
        receta: "",
        instrumento: InstrumentoEnum.ninguno,
        extra: ["Leche", "Plátano", "Fresas", "Joghurt"],
        variacion: ["Con leche", "Sin Leche"],
        dificultad: DificultadEnum.baja,
        calificacion: 3,
        imagen: [],
        ingredientes: ["Cereal"],
        link: [],
        tipo: [TipoEnum.desayuno, TipoEnum.cena],
        hambre: HambreEnum.poco,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.dulce,
    },
    {
        id: 4,
        nombre: 'Plato de Fruta',
        receta: "",
        instrumento: InstrumentoEnum.ninguno,
        extra: ["Joghurt", "Miel"],
        variacion: ["Plátano", "Pera", "Kiwi", "Fresas", "Piña"],
        dificultad: DificultadEnum.baja,
        calificacion: 2,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.desayuno, TipoEnum.antojo],
        hambre: HambreEnum.poco,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.dulce,
    },
    {
        id: 5,
        nombre: 'Huevos Estrellados',
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Sobre pan tostado", "Sobre tortilla", "Jamón", "Queso", "Pico de gallo", "Pesto", "Frijoles", "Salsa de frijol", "Salsa roja", "Tocino", "Champiñones", "Chorizo y papa", "Pimiento"],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 4,
        imagen: [],
        ingredientes: ["Huevos"],
        link: [],
        tipo: [TipoEnum.desayuno],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 6,
        nombre: 'Huevos al Sartén',
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Pimiento"],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 5,
        imagen: [],
        ingredientes: ["Huevos", "Pimiento", "Jitomate", "Cebolla", "Especias"],
        link: [],
        tipo: [TipoEnum.desayuno],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 7,
        nombre: 'Huevos Pochados',
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Sobre cama de champiñones", "Sobre cama de cebolla y carne molida", "Pesto"],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 4,
        imagen: [],
        ingredientes: ["Huevo", "Vinagre"],
        link: [],
        tipo: [TipoEnum.desayuno],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 8,
        nombre: 'Huevos Benedictinos',
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.alta,
        calificacion: 5,
        imagen: [],
        ingredientes: ["Huevos", "Vinagre", "Mantequilla", "Harina", "Jugo de limón"],
        link: [],
        tipo: [TipoEnum.desayuno],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 9,
        nombre: 'Huevos Revueltos',
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Jamón", "Queso", "Jalapeño", "Tinga", "Pimiento", "Cebolla", "Espinaca", "Tortillas"],
        variacion: ["Clásico", "Tacos", "Sandwich"],
        dificultad: DificultadEnum.baja,
        calificacion: 4,
        imagen: [],
        ingredientes: ["Huevos"],
        link: [],
        tipo: [TipoEnum.desayuno],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 10,
        nombre: 'Huevos a la Mexicana',
        sabor: SaborEnum.salado,
        extra: ["Tortillas", "Pan Tostado"],
        variacion: ["Clásico", "Tacos", "Sandwich"],
        dificultad: DificultadEnum.baja,
        calificacion: 5,
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        imagen: [],
        ingredientes: ["Huevos", "Cebolla", "Jitomate", "Jalapeño"],
        link: [],
        tipo: [TipoEnum.desayuno],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
    },
    {
        id: 11,
        nombre: 'Huevos Napolitanos',
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 5,
        imagen: [],
        ingredientes: ["Huevos", "Jitomate o Salsa de Tomate", "Queso"],
        link: [],
        tipo: [TipoEnum.desayuno],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 12,
        nombre: "Aguacates rellenos de Atún",
        receta: "",
        instrumento: InstrumentoEnum.ninguno,
        extra: [],
        variacion: ["Atún sencillo", "Atún preparado"],
        dificultad: DificultadEnum.baja,
        calificacion: 4,
        imagen: [],
        ingredientes: ["Aguacate", "Atún", "Cebolla", "Aceite de Olivo", "Jitomate"],
        link: [],
        tipo: [TipoEnum.desayuno, TipoEnum.cena, TipoEnum.antojo],
        hambre: HambreEnum.poco,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 13,
        nombre: 'Quesadillas',
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Jamón", "Tinga", "Champiñones", "Frijoles", "Calabaza", "Champiñones", "Atún", "Espinaca", "Pollo", "Pimiento", "Cebolla"],
        variacion: ["Tortilla de maíz", "Tortilla de harina"],
        dificultad: DificultadEnum.baja,
        calificacion: 5,
        imagen: [],
        ingredientes: ["Tortillas", "Queso"],
        link: [],
        tipo: [TipoEnum.desayuno, TipoEnum.cena, TipoEnum.antojo],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 14,
        nombre: "Molletes",
        receta: "Cortar bolillos a la mitad. Untar frijoles. Colocar queso y opcionalmente ingredienes extra. Hornear hasta que el queso esté derretido.",
        instrumento: InstrumentoEnum.horno,
        extra: ["Jamón", "Peperoni", "Salami", "Pico de gallo", "Salsa de tomate"],
        variacion: [],
        dificultad: DificultadEnum.baja,
        calificacion: 5,
        imagen: [],
        ingredientes: ["Bolillos", "Frijoles", "Queso"],
        link: ["https://www.youtube.com/watch?v=Tcy4qiPDjtk"],
        tipo: [TipoEnum.desayuno, TipoEnum.cena],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.preparar,
        relacionados: [5],
        sabor: SaborEnum.salado,
    },
    {
        id: 15,
        nombre: "Chilaquiles",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Huevo estrellado", "Cebolla"],
        variacion: [],
        dificultad: DificultadEnum.baja,
        calificacion: 5,
        imagen: [],
        ingredientes: ["Tortillas", "Salsa"],
        link: [],
        tipo: [TipoEnum.desayuno, TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 16,
        nombre: "Tamales",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: ["Canarios"],
        dificultad: DificultadEnum.alta,
        calificacion: 5,
        imagen: [],
        ingredientes: ["?"],
        link: [],
        tipo: [TipoEnum.desayuno],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.dulce,
    },
    {
        id: 17,
        nombre: "Waffles",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Helado", "Frutos rojos", "Miel", "Nutella", "Salsa de chocolate", "Azúcar glass"],
        variacion: [],
        dificultad: DificultadEnum.baja,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.desayuno, TipoEnum.cena],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.comprar,
        relacionados: [],
        sabor: SaborEnum.dulce,
    },
    {
        id: 18,
        nombre: "Sandwich",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Jamón", "Queso", "Atún", "Lechuga", "Jitomate", "Manzana y canela", "Mermelada"],
        variacion: ["Frío / Caliente"],
        dificultad: DificultadEnum.baja,
        calificacion: 3,
        imagen: [],
        ingredientes: ["Pan"],
        link: [],
        tipo: [TipoEnum.desayuno, TipoEnum.cena, TipoEnum.antojo],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 19,
        nombre: "Tortipizzas",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.baja,
        calificacion: 4,
        imagen: [],
        ingredientes: ["Tortillas de harina", "Salsa de tomate", "Queso", "Peperoni"],
        link: [],
        tipo: [TipoEnum.desayuno, TipoEnum.cena],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 20,
        nombre: "Enfrijoladas",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Crema", "Chipotle"],
        variacion: [],
        dificultad: DificultadEnum.alta,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.desayuno, TipoEnum.comida, TipoEnum.platofuerte, TipoEnum.cena],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 21,
        nombre: "Hot Cakes",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Miel", "Nutella", "Azúcar glass"],
        variacion: [],
        dificultad: DificultadEnum.baja,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.desayuno],
        hambre: HambreEnum.poco,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.dulce,
    },
    {
        id: 22,
        nombre: 'Pan de Dulce',
        receta: "",
        instrumento: InstrumentoEnum.ninguno,
        extra: [],
        variacion: ["Berlinesa", "Dona", "Panqué"],
        dificultad: DificultadEnum.baja,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.desayuno, TipoEnum.cena, TipoEnum.postre, TipoEnum.antojo],
        hambre: HambreEnum.poco,
        preparacion: PreparacionEnum.comprar,
        relacionados: [],
        sabor: SaborEnum.dulce,
    },
    {
        id: 23,
        nombre: 'Pan Tostado',
        receta: "",
        instrumento: InstrumentoEnum.ninguno,
        extra: ["Mantequilla y Azúcar", "Nutella", "Mermelada", "Queso Filadelfia"],
        variacion: [""],
        dificultad: DificultadEnum.baja,
        calificacion: 2,
        imagen: [],
        ingredientes: ["Pan"],
        link: [],
        tipo: [TipoEnum.desayuno, TipoEnum.cena, TipoEnum.antojo, TipoEnum.postre],
        hambre: HambreEnum.poco,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.dulce,
    },
    {
        id: 24,
        nombre: 'Galletas',
        receta: "",
        instrumento: InstrumentoEnum.ninguno,
        extra: [],
        variacion: ["Oreo", "Príncipe", "Leibniz"],
        dificultad: DificultadEnum.baja,
        calificacion: 2,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.cena, TipoEnum.postre, TipoEnum.antojo],
        hambre: HambreEnum.poco,
        preparacion: PreparacionEnum.comprar,
        relacionados: [],
        sabor: SaborEnum.dulce,
    },
    {
        id: 25,
        nombre: "Ensalada de atún",
        receta: "",
        instrumento: InstrumentoEnum.ninguno,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.baja,
        calificacion: 4,
        imagen: [],
        ingredientes: ["Lechuga", "Atún", "Aderezo César", "Jitomate", "Vinagre", "Pimienta"],
        link: [],
        tipo: [TipoEnum.cena, TipoEnum.comida, TipoEnum.ensalada, TipoEnum.platofuerte],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 26,
        nombre: 'Pizza',
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.baja,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte, TipoEnum.cena],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.comprar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 27,
        nombre: 'Torta',
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Lechuga", "Jitomate", "Queso","Lechuga"],
        variacion: ["Milanesa", "Chorizo", "Jamón", "Pimiento y Cebolla"],
        dificultad: DificultadEnum.baja,
        calificacion: 2,
        imagen: [],
        ingredientes: ["Pan", "Mayonesa"],
        link: [],
        tipo: [TipoEnum.cena, TipoEnum.comida, TipoEnum.platofuerte, TipoEnum.antojo],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 28,
        nombre: 'Wrap',
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Verduras"],
        variacion: ["Atún", "Pollo"],
        dificultad: DificultadEnum.media,
        calificacion: 3,
        imagen: [],
        ingredientes: ["Tortilla de Harina", "Proteína"],
        link: [],
        tipo: [TipoEnum.cena, TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 29,
        nombre: 'Tortitas de Atún',
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 2,
        imagen: [],
        ingredientes: ["Atún", "Cebolla", "Harina", "Huevo"],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte, TipoEnum.cena],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 30,
        nombre: 'Tacos Dorados',
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Lechuga", "Crema", "Salsa"],
        variacion: ["Tinga", "Pollo", "Papa y Chorizo", "Papa y Zanahoria", "Hongos"],
        dificultad: DificultadEnum.media,
        calificacion: 4,
        imagen: [],
        ingredientes: ["Tortillas", "Relleno"],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte, TipoEnum.cena, TipoEnum.desayuno],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 31,
        nombre: "Sushi",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: ["New York", "California"],
        dificultad: DificultadEnum.alta,
        calificacion: 5,
        imagen: [],
        ingredientes: ["Algas", "Arroz", "Mirín", "Vinagre de arroz", "Queso Filadelfia", "Aguacate", "Salmón"],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte, TipoEnum.cena],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 32,
        nombre: "Pasta",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Tiras de pollo", "Jamón", "Queso Parmesano","Champiñones"],
        variacion: ["Spaghetti / Fusili / etc", "Salsa de Fomate" , "A la crema" , "Mantequilla" , "Salsa de plátano y curry"],
        dificultad: DificultadEnum.media,
        calificacion: 3,
        imagen: [],
        ingredientes: ["Pasta"],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte, TipoEnum.guarnicion, TipoEnum.cena],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 33,
        nombre: "Crepa dulce",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Jarabe de Chocolate, Azúcar Glass"],
        variacion: ["Mermelada", "Queso Filadelfia", "Nutella"],
        dificultad: DificultadEnum.media,
        calificacion: 4,
        imagen: [],
        ingredientes: ["Huevos", "Harina", "Mantequilla", "Leche"],
        link: [],
        tipo: [TipoEnum.cena, TipoEnum.postre, TipoEnum.antojo],
        hambre: HambreEnum.poco,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.dulce,
    },
    {
        id: 34,
        nombre: 'Focaccia de Jamón Serrano y Queso',
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.baja,
        calificacion: 5,
        imagen: [],
        ingredientes: ["Pan de focaccia", "Jitomate", "Jamón serrano", "Queso Azul", "Lechuga", "Aceite de olivo"],
        link: [],
        tipo: [TipoEnum.desayuno, TipoEnum.cena, TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 35,
        nombre: "Milanesa",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Empanizada", "Cordon Blue"],
        variacion: ["Cerdo", "Pollo", "Res"],
        dificultad: DificultadEnum.media,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 36,
        nombre: "Pechuga de Pollo",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Salsa inglesa"],
        variacion: ["Asada", "Rellena de Champiñones envuelta en Tocino a la Crema"],
        dificultad: DificultadEnum.baja,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 37,
        nombre: "Bistec de Res",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.baja,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 38,
        nombre: "Alambre",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 39,
        nombre: "Pollo a la Naranja",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.alta,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 40,
        nombre: "Carne de Cerdo en Salsa Roja",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 41,
        nombre: "Brochetas",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: ["Pollo", "Camarones", "Cerdo", "Res"],
        dificultad: DificultadEnum.baja,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte, TipoEnum.cena],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 42,
        nombre: "Tinga",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: ["Pollo", "Champiñones"],
        dificultad: DificultadEnum.media,
        calificacion: 4,
        imagen: [],
        ingredientes: ["Chipotle", "Jitomates", "Cebolla"],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 43,
        nombre: "Albóndigas",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 44,
        nombre: "Tortitas",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Salsa de Tomate"],
        variacion: ["Carne Molida y Cebolla", "Papa y Chorizo", "Pollo", "Pollo y Espinaca", "Espinaca"],
        dificultad: DificultadEnum.media,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 45,
        nombre: "Pastel de Carne",
        receta: "",
        instrumento: InstrumentoEnum.horno,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 5,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 46,
        nombre: "Calabacitas",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: ["Costilla de Cerdo", "Pechuga de Pollo"],
        dificultad: DificultadEnum.media,
        calificacion: 5,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 47,
        nombre: "Fajitas de Pollo",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.baja,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 48,
        nombre: "Pollo al Horno con Verduras y Vino Tinto",
        receta: "",
        instrumento: InstrumentoEnum.horno,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.baja,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 49,
        nombre: "Tiras de Pollo Empanizadas",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 50,
        nombre: "Costillas BBQ",
        receta: "",
        instrumento: InstrumentoEnum.horno,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.baja,
        calificacion: 5,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.comprar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 51,
        nombre: "Hamburguesa",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Piña", "Manzana", "Jitomates deshidratados"],
        variacion: ["Pan Brioche", "Pan Tradicional"],
        dificultad: DificultadEnum.baja,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte, TipoEnum.cena],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 52,
        nombre: "Salmón",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Vinagre de Arroz y Mirín"],
        variacion: ["Sashimi", "Asado"],
        dificultad: DificultadEnum.baja,
        calificacion: 5,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 53,
        nombre: "Pescadillas",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 54,
        nombre: "Camarones",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: ["Empanizados","Envueltos en Tocino"],
        dificultad: DificultadEnum.media,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 55,
        nombre: "Lasagna de Berenjena",
        receta: "",
        instrumento: InstrumentoEnum.horno,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 3,
        imagen: [],
        ingredientes: ["Queso Ricotta"],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 56,
        nombre: "Pimiento Relleno",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Queso"],
        variacion: ["Carne Molida", "Arroz", "Tocino", "Cebolla"],
        dificultad: DificultadEnum.media,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 57,
        nombre: "Berenejna rellena de Pollo en Salsa de Tomate",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.alta,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 58,
        nombre: "Crepas saladas",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Salsa de Champiñones"],
        variacion: ["Espinaca y Queso", "Pollo" ],
        dificultad: DificultadEnum.media,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte, TipoEnum.desayuno, TipoEnum.cena],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 59,
        nombre: "Fritatta de Espinaca con Tomate",
        receta: "",
        instrumento: InstrumentoEnum.horno,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 60,
        nombre: "Choriqueso",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Cebolla", "Pimiento"],
        variacion: ["Tacos", "Totopos"],
        dificultad: DificultadEnum.baja,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 61,
        nombre: "Enrollados de Jamón y Spaghetti",
        receta: "",
        instrumento: InstrumentoEnum.horno,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 62,
        nombre: "Yakimeshi",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.alta,
        calificacion: 5,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte, TipoEnum.comida, TipoEnum.guarnicion],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 63,
        nombre: "Tepanyaki",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: ["Camarón", "Sirloin"],
        dificultad: DificultadEnum.alta,
        calificacion: 5,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 64,
        nombre: "Pizza",
        receta: "",
        instrumento: InstrumentoEnum.horno,
        extra: ["Salsa Inglesa","Catsup"],
        variacion: ["Salami", "Atún", "Peperoni", "Verduras", "Napolitana"],
        dificultad: DificultadEnum.baja,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.comprar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 65,
        nombre: "Enchiladas",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: ["Rojas","Verdes"],
        dificultad: DificultadEnum.media,
        calificacion: 5,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte,TipoEnum.cena],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 66,
        nombre: "Tostadas",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: ["Pollo", "Tinga"],
        dificultad: DificultadEnum.media,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 67,
        nombre: "Carne de Hamburguesa",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.baja,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.platofuerte],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 68,
        nombre: "Licuado",
        receta: "",
        instrumento: InstrumentoEnum.ninguno,
        extra: ["Proteína", "Cereal", "Plátano", "Mango", "Piña", "Frutos rojos"],
        variacion: ["Leche light", "Leche Regular", "Leche de soya", "Leche de avena", "Leche de almendra"],
        dificultad: DificultadEnum.baja,
        calificacion: 5,
        imagen: [],
        ingredientes: ["Leche"],
        link: [],
        tipo: [TipoEnum.desayuno, TipoEnum.cena, TipoEnum.bebida],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.dulce,
    },
    {
        id: 69,
        nombre: "Sopa de lentejas",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.baja,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.sopa],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.comprar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 70,
        nombre: "Agua de Limón",
        receta: "",
        instrumento: InstrumentoEnum.ninguno,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.baja,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.bebida],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.dulce,
    },
    {
        id: 71,
        nombre: "Verduras Salteadas",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.baja,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.guarnicion],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 72,
        nombre: "Leche",
        receta: "",
        instrumento: InstrumentoEnum.ninguno,
        extra: [],
        variacion: ["Leche light", "Leche Regular", "Leche de soya", "Leche de avena", "Leche de almendra"],
        dificultad: DificultadEnum.baja,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.bebida, TipoEnum.desayuno, TipoEnum.cena],
        hambre: HambreEnum.poco,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.dulce,
    },
    {
        id: 73,
        nombre: "Leche con Chocolate",
        receta: "",
        instrumento: InstrumentoEnum.ninguno,
        extra: [],
        variacion: ["Leche light", "Leche Regular", "Leche de soya", "Leche de avena", "Leche de almendra"],
        dificultad: DificultadEnum.baja,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.desayuno, TipoEnum.cena, TipoEnum.bebida],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.dulce,
    },
    {
        id: 74,
        nombre: "Leche con Proteína",
        receta: "",
        instrumento: InstrumentoEnum.ninguno,
        extra: [],
        variacion: ["Leche light", "Leche Regular", "Leche de soya", "Leche de avena", "Leche de almendra","Proteína sabor vainilla", "Proteína sabor crema de maní", "Proteína sabor crema chocolate"],
        dificultad: DificultadEnum.baja,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.desayuno, TipoEnum.cena, TipoEnum.bebida],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [71,72,73],
        sabor: SaborEnum.dulce,
    },
    {
        id: 75,
        nombre: "Malteada",
        receta: "",
        instrumento: InstrumentoEnum.ninguno,
        extra: ["Jarabe de chocolate"],
        variacion: ["Chocolate","Fresa","Vainilla"],
        dificultad: DificultadEnum.baja,
        calificacion: 5,
        imagen: [],
        ingredientes: ["Leche","Helado"],
        link: [],
        tipo: [TipoEnum.desayuno, TipoEnum.cena, TipoEnum.bebida],
        hambre: HambreEnum.mucho,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.dulce,
    },
    {
        id: 76,
        nombre: "Jugo",
        receta: "",
        instrumento: InstrumentoEnum.ninguno,
        extra: [],
        variacion: ["Naranja", "Manzana", "Fresa y plátano", "Uva"],
        dificultad: DificultadEnum.baja,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.desayuno, TipoEnum.cena, TipoEnum.bebida],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.comprar,
        relacionados: [],
        sabor: SaborEnum.dulce,
    },
    {
        id: 77,
        nombre: "Té",
        receta: "",
        instrumento: InstrumentoEnum.ninguno,
        extra: [],
        variacion: ["Frutos rojos", "Limón", "Jengibre", "Naranja"],
        dificultad: DificultadEnum.baja,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.desayuno, TipoEnum.cena, TipoEnum.bebida],
        hambre: HambreEnum.poco,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.dulce,
    },
    {
        id: 78,
        nombre: "Café",
        receta: "",
        instrumento: InstrumentoEnum.ninguno,
        extra: [],
        variacion: ["Negro","Capuccino","Con Leche"],
        dificultad: DificultadEnum.baja,
        calificacion: 1,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.desayuno, TipoEnum.cena, TipoEnum.bebida],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.amargo,
    },
    {
        id: 79,
        nombre: "Agua de frutas",
        receta: "",
        instrumento: InstrumentoEnum.ninguno,
        extra: [],
        variacion: ["Mango", "Piña", "Frutos rojos", "Fresa"],
        dificultad: DificultadEnum.baja,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.bebida],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.dulce,
    },
    {
        id: 80,
        nombre: "Vino Tinto",
        receta: "",
        instrumento: InstrumentoEnum.ninguno,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.baja,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.bebida],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.comprar,
        relacionados: [],
        sabor: SaborEnum.amargo,
    },
    {
        id: 81,
        nombre: "Vino Blanco",
        receta: "",
        instrumento: InstrumentoEnum.ninguno,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.baja,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.bebida],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.comprar,
        relacionados: [],
        sabor: SaborEnum.dulce,
    },
    {
        id: 82,
        nombre: "Papas a la Crema",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Romero", "Queso"],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.guarnicion],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 83,
        nombre: "Papas a la francesa",
        receta: "",
        instrumento: InstrumentoEnum.horno,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.guarnicion],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 84,
        nombre: "Puré de Papa",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Queso"],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.guarnicion],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 85,
        nombre: "Verduras Salteadas",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: ["Calabazas", "Pimientos", "Cebolla", "Mix italiano", "Zanahoria"],
        dificultad: DificultadEnum.baja,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.guarnicion],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 86,
        nombre: "Arroz blanco",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Verduras"],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.guarnicion],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 87,
        nombre: "Rajas con crema",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.guarnicion],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 88,
        nombre: "Frijoles refritos",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 5,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.guarnicion],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 89,
        nombre: "Queso al horno",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Pan"],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 5,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.guarnicion],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 90,
        nombre: "Jitomate con Aceite Balsámico",
        receta: "",
        instrumento: InstrumentoEnum.ninguno,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.guarnicion],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 91,
        nombre: "Crema de Frijol",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Chipotle"],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 5,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.sopa],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 92,
        nombre: "Crema de Champiñones",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.sopa],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 93,
        nombre: "Crema de Pimiento",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 5,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.sopa],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 94,
        nombre: "Crema de Elote",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 5,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.sopa],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 95,
        nombre: "Crema de Calabaza con Elote",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 5,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.sopa],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 96,
        nombre: "Consomé de Pollo",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: ["Arroz Blanco"],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.sopa],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [86],
        sabor: SaborEnum.salado,
    },
    {
        id: 97,
        nombre: "Sopa Bihún",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.sopa],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.comprar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 98,
        nombre: "Sopa Miso",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.sopa],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 99,
        nombre: "Sopa de Tomate",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.sopa],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.comprar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 100,
        nombre: "Sopa de Tortilla",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 5,
        imagen: [],
        ingredientes: ["Chile seco", "Totopos", "Queso", "Aguacate"],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.sopa],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 101,
        nombre: "Sopa de Pasta",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: ["Letras", "Fideos", "Municiones", "etc."],
        dificultad: DificultadEnum.media,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.sopa],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 102,
        nombre: "Sopa de Cebolla",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 5,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.sopa],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 103,
        nombre: "Sopa de verduras",
        receta: "",
        instrumento: InstrumentoEnum.estufa,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.media,
        calificacion: 3,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.sopa],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 104,
        nombre: "Ensalada César",
        receta: "",
        instrumento: InstrumentoEnum.ninguno,
        extra: ["Pollo"],
        variacion: [],
        dificultad: DificultadEnum.baja,
        calificacion: 5,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.ensalada],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [],
        sabor: SaborEnum.salado,
    },
    {
        id: 105,
        nombre: "Ensalada de Champiñones y Pimiento",
        receta: "",
        instrumento: InstrumentoEnum.ninguno,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.baja,
        calificacion: 4,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.ensalada],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [104,106],
        sabor: SaborEnum.salado,
    },
    {
        id: 106,
        nombre: "Ensalada de Durazno y Aderezo de Mermelada de Frutas",
        receta: "",
        instrumento: InstrumentoEnum.ninguno,
        extra: [],
        variacion: [],
        dificultad: DificultadEnum.baja,
        calificacion: 5,
        imagen: [],
        ingredientes: [],
        link: [],
        tipo: [TipoEnum.comida, TipoEnum.ensalada],
        hambre: HambreEnum.medio,
        preparacion: PreparacionEnum.preparar,
        relacionados: [104,105,25],
        sabor: SaborEnum.salado,
    },





]